import type { Metadata } from 'next';
import { Noto_Serif } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import ReduxProvider from './reduxProvider';

const notoSerif = Noto_Serif({
  variable: '--font-noto-serif',
  subsets: ['latin'],
});
export const metadata: Metadata = {
  title: 'Royal Place',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${notoSerif.variable}  antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ReduxProvider>
       
            {children}
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
