import type { Metadata } from 'next';
import { Noto_Serif, Krona_One } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import ReduxProvider from './reduxProvider';
import SmoothScroll from '@/components/SmoothScroll';


const notoSerif = Noto_Serif({
  variable: '--font-noto-serif',
  subsets: ['latin'],
});

const kronaOne = Krona_One({
  variable: '--font-krona-one',
  subsets: ['latin'],
  weight: '400',
});
export const metadata: Metadata = {
  title: 'Royal Place',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${notoSerif.variable} ${kronaOne.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ReduxProvider>
            <SmoothScroll>
              {children}
            </SmoothScroll>

          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
